[package]
name = "atto"
version = "0.0.4"
authors = ["Dariusz Depta <wisbery@users.noreply.github.com>"]
description = "Future project"
documentation = "https://docs.rs/atto"
repository = "https://github.com/wisbery/atto.git"
license = "MIT OR Apache-2.0"
edition = "2021"
